envelope/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^test/$', views.home), # APAGAR
    url(r'^base/$', views.base), # APAGAR
    url(r'^index/$', views.index),
    url(r'^confirmacao/$', views.confirmacao),
    url(r'^cadastro/$', views.cadastro),
    url(r'^confirmacao_cad/$', views.confirmacao_cad),
    url(r'^confirmacao_env/$', views.confirmacao_env),
    url(r'^details/(?P<pk>[0-9]+)/$', views.details),
    url(r'^devolucao/$', views.devolucao),
    url(r'^editar_env/(?P<pk>[0-9]+)/$', views.editar_env),
    url(r'^envelope/$', views.envelope),
    url(r'^gerar_relatorio/$', views.gerarrelatorio),
    url(r'^gerenciarenvelope/$', views.gerenciarenvelope),
    url(r'^listastatus/$', views.listastatus),
    url(r'^$', 'django.contrib.auth.views.login', 
    	{'template_name': 'envelope/login.html'}),
    url(r'^redefine/$', views.redefine),
    url(r'^relatorio/$', views.relatorio),
]

testes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^', include('envelope.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

envelope/models.py
from django.db import models
from django.core import validators

# Criacao da Tabela de Curso
class Curso(models.Model):
    Nome_Turma = (
        ('A', 'A'),
        ('B', 'B'),
    )
    curso_id = models.AutoField(primary_key=True)
    nome = models.CharField('Curso',max_length=60, null=False)
    turma = models.CharField('Turma',max_length=1, null=True, choices=Nome_Turma)
    
    def __str__(self):
        return self.nome
    
    class Meta:
        db_table ='Cont_Curso'
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['nome'] 
    

class Status(models.Model):
    Num_Status = (
        (1, 'Entregue'),
        (2, 'Entregue Atrasado'),
        (3, 'Pendente'),
        (4, 'Atrasado'),
    )
    status_id = models.AutoField(primary_key=True)
    status = models.IntegerField ('Status', choices=Num_Status, default='3')
    data_devolucao = models.DateTimeField('Entregue em', auto_now=True)
    def __str__(self):
        return str(self.status)
        
    class Meta:
        db_table ='Cont_Status'
        verbose_name = 'Status'
        verbose_name_plural = 'Status'
        ordering = ['data_devolucao']
        
        
class Prova(models.Model):
    Num_Estagio = (
        ('1', '1º Estágio'),
        ('2', '2º Estágio'),
        ('3', '3º Estágio'),
    )
    prova_id = models.AutoField(primary_key=True)
    estagio = models.CharField('Estágio', max_length=1, choices=Num_Estagio)
    data_prova = models.DateField('Data da Prova', null=False) # Data pra realizar prova
    data_limite = models.DateField('Data Limite', null=False) # Data de entregar a prova dps de realizada
    status_id = models.OneToOneField(Status, on_delete=models.CASCADE) 
    def __str__(self):
        return str(self.data_prova)
    
    class Meta:
        db_table ='Cont_Prova'
        verbose_name = 'Prova'
        verbose_name_plural = 'Provas'
        ordering = ['-estagio','data_prova']
        

class Disciplina(models.Model):
    Num_Periodo = (
        ('1', '1º Período'),('2', '2º Período'),('3', '3º Período'),
        ('4', '4º Período'),('5', '5º Período'),('6', '6º Período'),
        ('7', '7º Período'),('8', '8º Período'),
    )
    disciplina_id = models.AutoField(primary_key=True, unique = False)
    nome = models.CharField('Disciplina', max_length=60, null=False)
    periodo = models.CharField('Período', max_length=1, choices=Num_Periodo)
    prova = models.ForeignKey(Prova, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.nome
        
    def periodo_str(self):
        return self.periodo
    
    class Meta:
        db_table ='Cont_Disciplina'
        verbose_name = 'Disciplina'
        verbose_name_plural = 'Disciplinas'
        ordering = ['nome']
        
# db_column = 'nome'
# Criacao da Tabela de Professores      
class Professor(models.Model):
    professor_id = models.AutoField(primary_key=True, unique = False)
    nome = models.CharField('Nome', max_length=80, unique=True, null=False)
    matricula = models.CharField('Matricula', max_length=15, unique=True, null=False, blank=False)
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso)
    
    def __str__(self):
        return self.nome
        
    class Meta:
        db_table ='Cont_Professor'
        verbose_name = 'Professor'
        verbose_name_plural = 'Professores'
        ordering = ['nome']
        
                        
class Secretaria(models.Model):
    secretaria_id = models.AutoField(primary_key=True)
	#usuario_id = models.ForeignKey(User, on_delete = models.CASCADE)
    nome = models.CharField('Nome', max_length=80, null=False)
    cpf = models.CharField('CPF', max_length=14, unique=True)    
    
    def __str__(self):
        return self.nome
    
    class Meta:
        db_table ='Cont_Secretaria'
        verbose_name = 'Secretaria'
        verbose_name_plural = 'Secretarias'
        ordering = ['nome']
    
class Envelope (models.Model):
    envelope_id = models.AutoField(primary_key=True)
    professor = models.OneToOneField(Professor, unique = False)
    curso = models.OneToOneField(Curso, unique = False)
    disciplina = models.OneToOneField(Disciplina, unique = False)
    prova = models.OneToOneField(Prova)
    def __str__(self):
        return str(self.envelope_id)
    
    class Meta:
        db_table ='Cont_Envelopes'
        verbose_name = 'Envelope'
        verbose_name_plural = 'Envelopes'
        ordering = ['prova']
    

envelope/forms.py
from django import forms
from .models import Curso, Professor, Status, Secretaria, Prova, Disciplina, Envelope
from django.contrib.admin.widgets import AdminDateWidget 
        
class CursoForm(forms.ModelForm):
    
    class Meta:
        model = Curso
        #fields = '__all__'
        exclude = ['nome',]
       

# Criacao da Tabela de Professores      
class ProfessorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfessorForm, self).__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs['placeholder'] = 'Nome Completo'
        
    class Meta:
        model = Professor
        fields = ['nome','matricula',]
       

class StatusForm(forms.ModelForm):
    #def __init__(self, *args, **kwargs):
    #    super(StatusForm, self).__init__(*args, **kwargs)
    #    self.fields['status'].choices = 3
        
    class Meta:
        model = Status
        fields = '__all__'
       

class SecretariaForm(forms.ModelForm):
    
    class Meta:
        model = Secretaria
        exclude = ['secretaria_id',]
       

class ProvaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProvaForm, self).__init__(*args, **kwargs)
        self.fields['data_prova'].widget.attrs['placeholder'] = 'AAAA-MM-DD'
        self.fields['data_limite'].widget.attrs['placeholder'] = 'AAAA-MM-DD'
        
    class Meta:
        model = Prova
        exclude = ['status_id',]
       

class DisciplinaForm(forms.ModelForm):
    
    class Meta:
        model = Disciplina
        exclude = ['nome','prova',]
        
class EnvelopeForm(forms.ModelForm):
    
    class Meta:
        model = Envelope
        fields = '__all__'

class EditEnvelopeForm(forms.ModelForm):
    
    class Meta:
        model = Envelope
        fields = ['professor']
        
class ArticleForm(forms.Form):
    #cursos = Curso.objects.all()
    #for curso in cursos:
    #    nome = [curso.nome]
    title = forms.CharField()
    pub_date = forms.DateField()
    
class ProjectFilterForm(forms.Form):

    range = forms.ChoiceField(choices=[], required=False)

    def __init__(self, *args, **kwargs):
        super(ProjectFilterForm, self).__init__(*args, **kwargs)
        #oldest = Project.objects.first()
        #newest = Project.objects.last()
        #if oldest and newest:
        range_choices = []
        #for year in range(oldest.date.year, newest.date.year+1):
        #        range_choices.append('Spring {}'.format(year))
        #        range_choices.append('Fall {}'.format(year))
        self.fields['range'].choices = range_choices

envelope/views.py
from django.shortcuts import render, HttpResponse, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import EditEnvelopeForm, ProfessorForm, DisciplinaForm, CursoForm, ProvaForm, EnvelopeForm, StatusForm
from .models import Curso, Professor, Status, Secretaria, Prova, Disciplina, Envelope
from django.contrib import messages




from django.forms import modelform_factory #TESTE
import datetime # TESTE
from django.utils.datastructures import MultiValueDictKeyError


def base(request):   #APAGAR
    template_name = 'envelope/base.html'
    context={}
    
    return render(request,template_name , context)

def confirmacao(request, new_form, cursoForm, disciplinaForm):
    template_name = 'envelope/confirmacao_cadastro.html'
    context={
        'curso':cursoForm,
        'disciplina': disciplinaForm,
        'professor': new_form,
    }
    print (cursoForm)
    print (disciplinaForm)
    print (new_form)
    return render(request,template_name , context)

 # APAGAR
def home(request):
    context = {}
    
    template_name = 'envelope/cadastro_professor.html'
    if request.method == 'POST':
        pass
       #return redirect (views.confirmacao(request.POST), new_form , cursoForm, disciplinaForm)
    else:
        messages.info(request,"Erro, verifique os campos!") 
    context= {
        
    }
    return render(request,template_name , context)

#place = models.OneToOneField(Place,on_delete=models.CASCADE,primary_key=True, )
# p1 = Place(name='Demon Dogs', address='944 W. Fullerton')
# p1.save()
# p2 = Place(name='Ace Hardware', address='1013 N. Ashland')
# p2.save()
#Create a Restaurant. Pass the ID of the “parent” object as this object’s ID:

# r = Restaurant(place=p1, serves_hot_dogs=True, serves_pizza=False)
# r.save()

    
# a = ModelA(name="a")
# b = ModelB(name="b")
# a.b = b
# b.save()
# a.save()


def cadastro(request): #ARUMAR ADD CAMPO
    template_name = 'envelope/cadastro.html'
    context={}
    cursos = Curso.objects.all().order_by('nome')
    disciplinas = Disciplina.objects.all().order_by('nome')
    
    professorForm = ProfessorForm()
    cursoForm = CursoForm()
    disciplinaForm = DisciplinaForm()
    if request.method == 'POST':
        professorForm = ProfessorForm(request.POST)
        disciplinaForm = DisciplinaForm(request.POST)
        
        id_curso = request.POST["id_curso"]
        id_disciplina = request.POST["id_disciplina"]
        
        if professorForm.is_valid() and id_curso != '0' and id_disciplina != '0' :
            print ('PASSOU')    # APAGAR
            test_curso = get_object_or_404(Curso, pk=id_curso)
            test_disciplina = get_object_or_404(Disciplina, pk=id_disciplina)
            
            new_prof = professorForm.save(commit = False)
            new_prof.curso = test_curso
            new_prof.disciplina = test_disciplina
            new_prof.save()
            context['success'] = True
            messages.success(request,"Registro "+str(new_prof)+" inserido com sucesso!") #teste
        else:
            messages.info(request,"Erro, verifique os campos!") 
    
    context= {
        'professorForm':professorForm,
        'cursoForm':cursoForm,
        'disciplinaForm':disciplinaForm,
        'cursos': cursos,
        'disciplinas':disciplinas,
    }  
    return render(request,template_name , context)


def confirmacao_cad(request):
    template_name = 'envelope/confirmacao_cadastro.html'
    context={}
    
    return render(request,template_name , context)


def confirmacao_env(request):
    template_name = 'envelope/confirmacao_envelope.html'
    context={}
    
    return render(request,template_name , context)


def details(request, pk):
    template_name = 'envelope/details.html'
    envelope = Envelope.objects.get(envelope_id = pk)
    context={
        'envelope' : envelope,
    }
    return render(request,template_name , context)


def devolucao(request):
    template_name = 'envelope/devolucao.html'
    context={}
    
    return render(request,template_name , context)


def editar_env(request, pk):
    template_name = 'envelope/editar_envelope.html'
    cursos = Curso.objects.all().order_by('nome')
    professores = Professor.objects.all().order_by('nome')
    disciplinas = Disciplina.objects.all().order_by('nome')
    
    envelope = Envelope.objects.get(envelope_id = pk)
    context={
        'envelope':envelope,
        'professores': professores,
        'cursos':cursos,
        'disciplinas':disciplinas,
    }
    
    return render(request,template_name , context)


def envelope(request):
    template_name = 'envelope/envelope.html'
    context={}
    cursos = Curso.objects.all().order_by('nome')
    professores = Professor.objects.all().order_by('nome')
    disciplinas = Disciplina.objects.all().order_by('nome')
    
    cursoForm = CursoForm()
    disciplinaForm = DisciplinaForm()
    provaForm = ProvaForm()
    envelopeForm = EnvelopeForm()
    statusForm = StatusForm()
    
    if request.method == 'POST':
        disciplinaForm = DisciplinaForm(request.POST)
        provaForm = ProvaForm(request.POST)
        cursoForm = CursoForm(request.POST)
        
        id_curso = request.POST["id_curso"]
        id_disciplina = request.POST["id_disciplina"]
        id_professor = request.POST["id_professor"]
        #estagio = request.POST["estagio"]
        #print (provaForm.cleaned_data['data_prova'])
        #print (id_curso)        # APAGAR
        #print (id_professor)    # APAGAR
        print (request.POST)
        print (provaForm.is_valid())
        print (disciplinaForm.is_valid())
        #statusForm.status = '3'
        #print (statusForm.is_valid())
        
        #if id_curso != '0' and id_disciplina != '0' and id_professor != '0' and estagio != '0':
        if provaForm.is_valid() and id_disciplina != '0' and id_professor != '0' and id_curso != '0':
            print("PASSOU")     # APAGAR
            test_curso = get_object_or_404(Curso, pk=id_curso)
            test_disciplina = get_object_or_404(Disciplina, pk=id_disciplina)
            test_professor = get_object_or_404(Professor, pk=id_professor)
            
            #statusForm.save()
            status = statusForm.save(commit = False)
            status.status = 3
            status.save()
            
            new_prova = provaForm.save(commit = False)
            new_prova.status_id = status
            #new_prova.estagio = estagio
            new_prova.save()
            
            new_envelope = envelopeForm.save(commit = False)
            new_envelope.professor = test_professor
            new_envelope.curso = test_curso
            new_envelope.disciplina = test_disciplina
            new_envelope.prova = new_prova
            new_envelope.save()
            context['success'] = True
            messages.success(request,"Registro inserido com sucesso!")
            return redirect('envelope/envelope.html')
        else:
            messages.info(request,"Erro, verifique os campos!")
    
    context = {
        'professores': professores,
        'cursos':cursos,
        'disciplinas':disciplinas,
        'cursoForm': cursoForm,
        'disciplinaForm' : disciplinaForm,
        'provaForm':provaForm,
        'envelopeForm':envelopeForm,
    }
    return render(request,template_name , context)


def gerarrelatorio(request):
    template_name = 'envelope/gerar_relatorio.html'
    estagio='a'
    status=''
    if( request.method == 'POST'):
        estagio = request.POST["estagio"]
        status = request.POST["status"]
        print(estagio)
        print(status)
        context={
            'estagio':estagio,
            'status':status,
        }
    else:
        context={}
    
    return render(request,template_name , context)


def gerenciarenvelope(request):
    template_name = 'envelope/gerenciarenvelope.html'
    context={}
    professores = Professor.objects.all().order_by('nome')
    cursos = Curso.objects.all().order_by('nome')
    disciplinas = Disciplina.objects.all().order_by('nome')
    prova = Prova.objects.all().order_by('data_prova')
    
    cursoForm = CursoForm()
    disciplinaForm = DisciplinaForm()
    context = {
        'professores':professores,
        'cursos':cursos,
        'disciplinas':disciplinas,
        'cursoForm':cursoForm,
        'disciplinaForm' : disciplinaForm,
    }
    return render(request,template_name , context)

def index(request):
    template_name = 'envelope/index.html'
    context={}
    envelopes = Envelope.objects.all()
    #envelope = request["a"] # TESTE
    #print(envelope.id)
    if (envelopes):
        context = {
        'envelopes' : envelopes,
    }    
    else:
        messages.info(request,"Não possui envelope cadastrado!")
    
    return render(request,template_name , context)


def listastatus(request):
    template_name = 'envelope/listastatus.html'
    context={}
    
    return render(request,template_name , context)


def login(request):
    template_name = 'envelope/login.html'
    context={}
    
    return render(request,template_name , context)


def redefine(request):
    template_name = 'envelope/redefine.html'
    context={}
    
    return render(request,template_name , context)


def relatorio(request):
    template_name = 'envelope/relatorio.html'
    context={}
    
    print(estagio)
    return render(request,template_name , context)

envelope/templates/envelope/base.html
{% load staticfiles %}

<!DOCTYPE <!DOCTYPE html>
<html>
<head>
	<meta character="utf-8">	
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/logo_unipe.png' %}">
    
    {% block title %} <title>Controle de Envelope</title> {% endblock %}
	
	<!--chamando bootstrap-->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!--chamando stylesheet-->
	{% block css %} <link rel="stylesheet" href="{% static 'css/style_cadastro.css' %}"> {% endblock %}

</head>

<body>
	<aside class="sidebar-left">

    <a alt="UNIPÊ | Centro Universitário de João Pessoa" title="UNIPÊ | Centro Universitário de João Pessoa" 
    class="company-logo" href="{% url 'envelope.views.index' %}"><img src="{% static 'images/logo-unipe.png' %}"></a>

    <div class="sidebar-links">
      <a  href="{% url 'envelope.views.cadastro' %}">Cadastrar Professor</a>
      <a  href="{% url 'envelope.views.envelope' %}">Inserir Envelope</a>
      <a  href="{% url 'envelope.views.gerenciarenvelope' %}">Gerenciar Envelope</a>
      <a  href="{% url 'envelope.views.gerarrelatorio' %}">Gerar Relatório</a>
      <a  href="{% url 'django.contrib.auth.views.login' %}">Sair</a>
    </div>

  </aside>

    {% block content %}
    
    {% endblock %}
    
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!--
    <script src="http://code.jquery.com/jquery-1.8.2.js"></script>
    <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
    -->
    
    {% block jquery%}
    
    {% endblock %}
	<!--chamando o js-->
	{% block js %}<script src="{% static 'js/bootstrap.js' %}"></script> {% endblock %}

</body>
</html>

envelope/templates/envelope/cadastro.html
{% extends 'envelope/base.html' %}
{% load staticfiles %}

	  {% block title %} <title>Cadastro</title> {% endblock %}
	  {% block css %} <link rel="stylesheet" href="{% static 'css/style_cadastro.css' %}"> {% endblock %}
      
      {% block content %}

      <div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main">
          <h2 class="sub-header">Cadastrar Professor</h2>
          
          <form class="form-horizontal" method="POST">
          {% csrf_token %}
              
              {% if messages %}
                  {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                  {% endfor %}
              {% endif %}
          
              {% for field in professorForm %}
              <div class="form-group">
                <label for="text" class="col-sm-2 control-label">{{ field.label_tag }}</label>
                <div class="col-sm-10">
                  {{ field }}
                  
                  {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                  {% endif %}
                </div>
              </div>
              {% endfor %}


              <div class="form-group">
                <label for="text" class="col-sm-2 control-label">Curso</label>
                <div class="col-sm-9">
                  <select class="form-control" name = "id_curso">
                    <option value='0'>--------</option>
                    {% for curso in cursos %}
                        <option value = "{{curso.curso_id}}">{{curso.nome}}</option>
                    {% endfor %}
                  </select>
                </div>
                <button class="btn btn-default" type="button">
                      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
              </div>
              
              {% for field in cursoForm %}
              <div class="form-group">
                  <label for="text" class="col-sm-2 control-label">{{ field.label_tag }}</label>
                  <div class="col-sm-9">
                    {{ field }}
                  </div>
                  <button class="btn btn-default" type="button">
                      <span class="glyphicon glyphicon-plus"></span>
                  </button>
              </div>
              {% endfor %}

              <div class="form-group">
                <label for="text" class="col-sm-2 control-label">Disciplina</label>
                <div class="col-sm-9">
                  <select class="form-control" name ="id_disciplina">
                    <option value='0'>--------</option>
                    {% for disciplina in disciplinas %}
                        <option value='{{disciplina.disciplina_id}}'>{{disciplina.nome}}</option>
                    {% endfor %}
                  </select>
                </div>
                <button class="btn btn-default" type="button">
                      <span class="glyphicon glyphicon-plus"></span>
                </button>
              </div>
              

              {% for field in disciplinaForm %}
              <div class="form-group">
                <label for="text" class="col-sm-2 control-label">{{ field.label_tag }}</label>
                <div class="col-sm-9">
                  {{ field }}
                </div>
                <button class="btn btn-default" type="button">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
              </div>
              {% endfor %}

              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default" role="button">Cadastrar</button>
                  <a href="{% url 'envelope.views.cadastro' %}" class="btn btn-default" role="button">Limpar Tudo</a>
                </div>
              </div>
          </form>
      </div>
      {% endblock %}

envelope/templates/envelope/envelope.html
{% extends 'envelope/base.html' %}
{% load staticfiles %}

  {% block title %} <title>Envelope</title> {% endblock %}
  {% block css %} <link rel="stylesheet" href="{% static 'css/style_envelope.css' %}"> {% endblock %}
    
  {% block content %}

    <div class="col-sm-9 col-sm-offset-3 col-md-9 col-md-offset-2 main">
        <h2 class="sub-header">Inserir Novo Envelope</h2>
        
        <form class="form-horizontal" method="post">
        {% csrf_token %}   
          {% if messages %}
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
          {% endif %}
            <div class="form-group">
              <label for="text" class="col-sm-2 control-label">Professor</label>
              <div class="col-sm-10">
                <select class="form-control" name="id_professor">
                  <option value='0'>--------</option>
                  {% for professor in professores %}
                        <option value = "{{professor.professor_id}}">{{professor.nome}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>

            <div class="form-group">
              <label for="text" class="col-sm-2 control-label">Curso</label>
              <div class="col-sm-10">
                <select class="form-control" name="id_curso">
                  <option value='0'>--------</option>
                  {% for curso in cursos %}
                      <option value = "{{curso.curso_id}}">{{curso.nome}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>

            {% for field in cursoForm %}
            <div class="form-group">
                <label for="text" class="col-sm-2 control-label">{{ field.label_tag }}</label>
                <div class="col-sm-10">
                  {{ field }}
                </div>
            </div>
            {% endfor %}
            
            <div class="form-group">
              <label for="text" class="col-sm-2 control-label">Disciplina</label>
              <div class="col-sm-10">
                <select class="form-control" name="id_disciplina">
                  <option value='0'>--------</option>
                  {% for disciplina in disciplinas %}
                      <option value='{{disciplina.disciplina_id}}'>{{disciplina.nome}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            
            {% for field in disciplinaForm %}
            <div class="form-group">
              <label for="text" class="col-sm-2 control-label">{{ field.label_tag }}</label>
              <div class="col-sm-10">
                {{ field }}
              </div>
            </div>
            {% endfor %}
            
            {% for field in provaForm %}
            <div class="form-group">
              <label for="text" class="col-sm-2 control-label">{{ field.label_tag}}</label>
              <div class="col-sm-10">
                {{ field }}
                {% if field.errors %}
                <ul class="errorlist">
                    {% for error in field.errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
              </div>
            </div>
            {% endfor %}
            
            
          
            
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button id='enviar' type="submit" class="btn btn-default" role="button">Inserir</button>
                <a href="{% url 'envelope.views.envelope' %}" class="btn btn-default" role="button">Limpar Tudo</a>
                <a class="btn btn-default" href="#" role="button">Excluir</a>
              </div>
            </div>
        </form> 
    </div>
   {% endblock %}
   
   {% block jquery%}
     <script src="{% static 'js/jquery-1.8.2.js' %}"></script>
      <script src="{% static 'js/jquery-ui.js' %}"></script>
      <script>
        $(function() {
            $( "#id_data_prova" ).datepicker({
                showOn: "button",
                buttonImage: "{% static 'images/Calendar.png' %}",
                buttonImageOnly: true,
                showButtonPanel:true,
                dateFormat: 'yy-mm-dd',
                showOtherMonths: true,
                selectOtherMonths: true,
                dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
                dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
            });
        });
        
        $(function() {
            $( "#id_data_limite" ).datepicker({
                showOn: "button",
                buttonImage: "{% static 'images/Calendar.png' %}",
                buttonImageOnly: true,
                showButtonPanel:true,
                dateFormat: 'yy-mm-dd',
                showOtherMonths: true,
                selectOtherMonths: true,
                dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
                dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
            });
        });
      </script>
   {% endblock %}